### ISSUE TITLE
CUDA 10.2 support

### ISSUE THREAD

**Issue by mausch** [valayDave/metaflow-on-kubernetes-docs#1]
Hi and thanks for all the work you've put into this repo!

I was reading https://github.com/valayDave/metaflow-on-kubernetes-docs/blob/master/gpu.md#specs ... just wanted to let you know I've recently been through this mess of enabling CUDA on our kubernetes cluster. I was able to get CUDA 10.2 running on kops+k8s 1.12 using https://github.com/elevate/nvidia-device-plugin instead of the `dcwangmit01/nvidia-device-plugin` image kops mentions in its docs.

**Comment by valayDave** [comment]
This is gold. Thank you. I will test this with Kubernetes version 1.16 on KOPS. https://github.com/elevate/nvidia-device-plugin are using KOPS with 1.16

**Comment by mausch** [comment]
That `elevate` fork is mine, I just made a minor change to support 1.12. If you're on 1.16 try the original first https://github.com/cicdteam/nvidia-device-plugin .
Also you'll probably have to play around with the image tags... I tried `tesla-440.64.00` first and it didn't work for me, but then I was able to get it to work with `tesla-440.33.01`.

**Comment by valayDave** [comment]
I tested it on Kubernetes 1.16.7 with Cuda 10.2. It worked Perfectly !. Thank you :D. I Will add that to this. I have made my own docker image which I am referencing as execContainer.

**Comment by valayDave** [comment]
https://github.com/valayDave/metaflow-on-kubernetes-docs/commit/4b6e7afe9085b15b8b23961d477d190c90640c1c

Tested it with Kubernetes version 1.16.7. Cuda 10.2 Worked like a charm.
